apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-pv
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /home/ubuntu/assignment/consumer/