apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      volumes:
      - name: app
        persistentVolumeClaim:
          claimName: app-pvc
      containers:
      - name: consumer
        image: consumer
        args: ["consumer.py", "group4"]
        imagePullPolicy: Never
        volumeMounts:
        - name: app
          mountPath: /app