apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  replicas: 4
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: consumer
          args: ["consumer.py", "{{TOPIC}}"]
          volumeMounts:
            - name: config-vol
              mountPath: ./auth
      volumes:
        - name: config-vol
          configMap:
            name: kafka-auth
            items:
              - key: kafka.truststore.pkcs12
                path: kafka.truststore.pkcs12
              - key: kafka.keystore.pkcs12
                path: kafka.keystore.pkcs12
              - key: ca.crt
                path: ca.crt